server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      discovery:
        hostname: localhost
        port: 8500
        service-name: ${spring.application.name}